# Generated by Django 5.1.7 on 2025-05-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(db_column='idCarrera', primary_key=True, serialize=False)),
                ('nom_carrera', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(db_column='idComuna', primary_key=True, serialize=False)),
                ('nom_comuna', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('nom_genero', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id_track', models.AutoField(db_column='idTrack', primary_key=True, serialize=False)),
                ('nom_track', models.CharField(max_length=30)),
                ('descripcion', models.CharField(default='Descripción del track', max_length=250)),
                ('imagen', models.ImageField(default='images/default_track.png', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='TrackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
