<<<<<<< Updated upstream
# Generated by Django 5.1.7 on 2025-05-27 19:15
=======
# Generated by Django 5.1.7 on 2025-05-26 03:53
>>>>>>> Stashed changes

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='id_usuario',
            field=models.ForeignKey(db_column='idUsuario', limit_choices_to={'rol': 'docente'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
<<<<<<< Updated upstream
        migrations.AddField(
            model_name='trackrequest',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trackrequest',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='administrador.track'),
        ),
=======
>>>>>>> Stashed changes
    ]
