# Generated by Django 5.1.7 on 2025-05-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackrequest',
            name='id',
        ),
        migrations.AddField(
            model_name='trackrequest',
            name='id_solicitud',
            field=models.AutoField(db_column='idSolicitud', default=0, primary_key=True, serialize=False),
        ),
    ]
