# Generated by Django 5.2 on 2025-06-10 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAdministrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('administrador', models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_administrador', to=settings.AUTH_USER_MODEL)),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.genero')),
            ],
        ),
    ]
