# Generated by Django 5.1.7 on 2025-05-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='descripcion',
            field=models.CharField(default='Descripción del track', max_length=250),
        ),
        migrations.AddField(
            model_name='track',
            name='imagen',
            field=models.ImageField(default='images/default_track.png', upload_to='images/'),
        ),
    ]
