# Generated by Django 5.1.7 on 2025-05-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_remove_trackrequest_id_trackrequest_id_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackrequest',
            name='id_solicitud',
            field=models.AutoField(db_column='idSolicitud', primary_key=True, serialize=False),
        ),
    ]
