# Generated by Django 5.1.7 on 2025-05-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_alter_trackrequest_id_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id_tipo_evento', models.AutoField(primary_key=True, serialize=False, verbose_name='idTipoEvento')),
                ('nombre_tipo_evento', models.CharField(max_length=25)),
            ],
        ),
    ]
