# Generated by Django 5.1.7 on 2025-05-28 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_tipoevento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReunionTrack',
            fields=[
                ('id_reunion', models.AutoField(db_column='idReunion', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], default='presencial', max_length=20)),
                ('link_virtual', models.URLField(blank=True, help_text='Enlace para reuniones virtuales', null=True)),
                ('ubicacion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('id_docente', models.ForeignKey(db_column='idDocente', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuniones', to='administrador.track')),
            ],
        ),
    ]
