# Generated by Django 5.2 on 2025-06-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('docente', 'Docente'), ('administrador', 'Administrador')], max_length=20),
        ),
    ]
