# Generated by Django 5.1.7 on 2025-05-28 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_alter_trackrequest_id_solicitud'),
        ('login', '0002_user_id_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.track'),
        ),
    ]
