<<<<<<< Updated upstream
# Generated by Django 5.1.7 on 2025-05-28 20:27
=======
# Generated by Django 5.1.7 on 2025-05-26 03:53
>>>>>>> Stashed changes

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0005_tipoevento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False, verbose_name='id_evento')),
                ('nombre_evento', models.CharField(max_length=50)),
                ('ubicacion_evento', models.CharField(max_length=100)),
                ('fecha_evento', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('infografia', models.ImageField(upload_to='images/')),
                ('docente', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_tipo_evento', models.ForeignKey(db_column='idTipoEvento', on_delete=django.db.models.deletion.CASCADE, to='administrador.tipoevento')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.carrera')),
                ('docente', models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_docente', to=settings.AUTH_USER_MODEL)),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.genero')),
            ],
        ),
    ]
