# Generated by Django 5.2 on 2025-06-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocentePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False, verbose_name='id_evento')),
                ('nombre_evento', models.CharField(max_length=50)),
                ('ubicacion_evento', models.CharField(max_length=100)),
                ('fecha_evento', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('infografia', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
