# Generated by Django 5.2 on 2025-05-25 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('nom_genero', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_docente',
            fields=[
                ('id_docente', models.AutoField(db_column='idDocente', primary_key=True, serialize=False)),
                ('p_nombre', models.CharField(max_length=15)),
                ('s_nombre', models.CharField(max_length=15)),
                ('apellido_pat', models.CharField(max_length=15)),
                ('apellido_mat', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='images/')),
                ('genero', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='docente.genero')),
            ],
        ),
    ]
