# Generated by Django 5.2 on 2025-06-05 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0002_initial'),
        ('docente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='docentepost',
            name='docente',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='posts_docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='docentepost',
            name='track',
            field=models.ForeignKey(db_column='idTrack', on_delete=django.db.models.deletion.CASCADE, related_name='posts_track', to='administrador.track'),
        ),
        migrations.AddField(
            model_name='evento',
            name='docente',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento',
            name='id_tipo_evento',
            field=models.ForeignKey(db_column='idTipoEvento', on_delete=django.db.models.deletion.CASCADE, to='administrador.tipoevento'),
        ),
        migrations.AddField(
            model_name='perfildocente',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.carrera'),
        ),
        migrations.AddField(
            model_name='perfildocente',
            name='docente',
            field=models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfildocente',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.genero'),
        ),
    ]
