# Generated by Django 5.1.7 on 2025-05-28 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_tipoevento'),
        ('docente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocentePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('docente', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='posts_docente', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(db_column='idTrack', on_delete=django.db.models.deletion.CASCADE, related_name='posts_track', to='administrador.track')),
            ],
        ),
    ]
