# Generated by Django 5.2 on 2025-06-14 02:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_perfiladministrador'),
        ('docente', '0003_postproyectodocente_reunionproyectodocente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocentePost',
            new_name='TrackPost',
        ),
    ]
