# Generated by Django 5.2 on 2025-07-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0004_rename_docentepost_trackpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfildocente',
            name='direccion',
        ),
    ]
