# Generated by Django 5.1.7 on 2025-05-27 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('idTrack', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('imagen', models.ImageField(upload_to='images/')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks_asignados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
