<<<<<<< Updated upstream
# Generated by Django 5.1.7 on 2025-05-27 19:15
=======
# Generated by Django 5.1.7 on 2025-05-26 03:53
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil_alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nom_proyecto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('fecha_inicio', models.DateField()),
                ('imagen', models.ImageField(upload_to='images/')),
                ('objetivo', models.CharField(max_length=200)),
                ('num_integrantes', models.IntegerField()),
            ],
        ),
    ]
