# Generated by Django 5.2 on 2025-06-05 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0002_initial'),
        ('alumno', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_alumno',
            name='alumno',
            field=models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_alumno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfil_alumno',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.carrera'),
        ),
        migrations.AddField(
            model_name='perfil_alumno',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.genero'),
        ),
        migrations.AddField(
            model_name='perfil_alumno',
            name='track_interes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.track'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='id_track',
            field=models.ForeignKey(db_column='idTrack', on_delete=django.db.models.deletion.CASCADE, to='administrador.track'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='jefe_proyecto',
            field=models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, to='alumno.perfil_alumno'),
        ),
        migrations.AddField(
            model_name='proyectorequest',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyectorequest',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='alumno.proyecto'),
        ),
    ]
