# Generated by Django 5.2 on 2025-06-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0004_alter_proyecto_jefe_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil_alumno',
            name='correo',
        ),
    ]
