# Generated by Django 5.2 on 2025-06-13 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0005_remove_perfil_alumno_correo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoPost',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='alumno.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ReunionProyecto',
            fields=[
                ('id_reunion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='Reunión de Proyecto', max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], default='presencial', max_length=20)),
                ('link_virtual', models.URLField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuniones', to='alumno.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='IntegranteProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='alumno.proyecto')),
            ],
            options={
                'unique_together': {('proyecto', 'alumno')},
            },
        ),
    ]
