# Generated by Django 5.2 on 2025-07-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0006_proyectopost_reunionproyecto_integranteproyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil_alumno',
            name='direccion',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='respuesta_admin',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
